service: items-routes-route-optimisation
runtime: python39
instance_class: B2

basic_scaling:
  max_instances: 5
  idle_timeout: 20m

entrypoint: gunicorn -b :$PORT --workers 2 --threads 4 --timeout 60 main:app

env_variables:
  GOOGLE_MAPS_API_KEY: AIzaSyA8Lm44z4-JVk10-PoSmcX5uX61QtAcrHk
  SECRET_KEY: route-optimization-secret-key
  GOOGLE_CLOUD_PROJECT_ID: maibach-items-routes

handlers:
- url: /static
  static_dir: static
  secure: always
  http_headers:
    Cache-Control: public, max-age=3600

- url: /static/css
  static_dir: static/css
  secure: always
  http_headers:
    Cache-Control: public, max-age=3600

- url: /static/js
  static_dir: static/js
  secure: always
  http_headers:
    Cache-Control: public, max-age=3600

- url: /static/images
  static_dir: static/images
  secure: always
  http_headers:
    Cache-Control: public, max-age=3600

- url: /.*
  script: auto
  secure: always 
  